### ISSUE TITLE
[Question] How handle multi page ?

### ISSUE THREAD

**Issue by kamelbou** [Tallyb/cucumber-playwright#385]
Hello !

Thanks a lot for this repo :)

In our tests, we need to handle multiple pages. I mean that, we can open multiple tab and want to interact with them. If in your Before step you write `this.page = ...` it will be propagated to other cucumber steps `Given` `When` `Then` but it is always the same page.

To be more clear, If I write a scenario like below, playwright will open two tabs, but using your design, how can I interact with both of them  whereas this.page represent only one object (the current page...).

```
Given Go to the playwright website
Given Go to the playwright website
```

Thanks a lot !

**Comment by Tallyb** [comment]
In this project, I have only used one page. However, it is possible to have multiple pages. you will need to store them with some reference on your world object. For example, you can have different users and reference them by the usernames.

This is how I do it in my project: 
```
"User1" is going to page "playwright.dev"
```

And then I have in the world object a "sessions" object as follows: 
```
sessions: {
   user1: {
      page: <reference to the page object>
  },
  user2: {
      page: <reference to the page object>
  }
}
```
In the step above I am creating `this.sessions.user1 = page`
You can have a currentSession property that holds the current page object, and a step to switch the currentSession. 
```
Current active user is "user1". 
```
And this step assigns the currentSession to the relevant page. 
In all your steps you will need to use the `this.currentSession` instead of page. 
I hope this makes sense.
