### ISSUE TITLE
Error when execution Fail

### ISSUE THREAD

**Issue by JSLadeo** [Tallyb/cucumber-playwright#554]
Hello , 
When i provoke an error , the run fail with following error: 
"tracing.stop: ENOENT: no such file or directory, copyfile 'C:\Users\*****\AppData\Local\Temp\playwright-artifacts-yGjurr\2124ba7357bdb49ae069010cafb0d9eb.trace.zip' -> 'C:\Users\*****\Documents\*******\git repo\cucumber-playwright\traces\Change-theme-2022-12-12T17:43:55trace.zip'
          at CustomWorld.<anonymous> (C:\Users\*******\Documents\********\git repo\cucumber-playwright\src\support\common-hooks.ts:58:41)"

Any idea for correct this?
When no error , it work well.
I am on windows with node 16.15.1

Thanks

**Comment by Tallyb** [comment]
probably the folder was not created on your machine. On windows I think you should create it manually

**Comment by Kumasta** [comment]
Had a colleague who had this issue and I did not. He was running on windows and I was on Linux.
The issue is the name of the trace file it wants to save contains colons ":" and windows does not allow that character in file/folder names.

We replaced all of the colons in the path name and it can now save as normal.

I think the trace stop function needs to replace all the : with another character or remove altogether for windows users.
